# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  direnv:
    desc: Run direnv hooks
    cmd: direnv allow .
    status:
    - "[[ $(direnv status --json | jq '.state.foundRC.allowed') == 0 ]]"
    - "[[ $(direnv status --json | jq '.state.loadedRC.allowed') == 0 ]]"
